apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Name der ClusterRole
  name: chaos-mesh-manager
rules:
- apiGroups:
  - chaos-mesh.org
  resources:
  - workflows
  verbs:
  - get
  - list
  - create
  - update
  - delete
