apiVersion: v1
kind: Service
metadata:
  name: central-node
  namespace: central-network
spec:
  selector:
    app: central-node
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP  # Intern im Cluster erreichbar
---
apiVersion: v1
kind: Service
metadata:
  name: central-service
  namespace: central-network
spec:
  type: NodePort  # Ermöglicht Zugriff von außerhalb des Clusters
  selector:
    app: central-node
  ports:
    - protocol: TCP
      port: 5000  # Port für den Zugriff von außen (geht nicht)
      targetPort: 5000  # Port im Container
      nodePort: 30020  # Port auf dem Host (30001-32767 erlaubt)