FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

# Arbeitsverzeichnis setzen
WORKDIR /app

# Abhängigkeiten installieren
RUN pip install Flask requests
RUN pip install kubernetes flask

# Flask-App kopieren
COPY workerNode.py .

# Environment-Variablen setzen
ENV NAME=node-default
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_PORT=5000 

# Container starten
CMD ["python3", "./workerNode.py"]